### PR TITLE
Move unpublishing a contact to the interactor

### PR DESCRIPTION
**Pull request by jamiecobbett**
This collects all the parts of removing a contact into one place.

### CODE REVIEW

**Comment by fatbusinessman** [comment]
Does that mean the `deregister_contact` method can disappear from `Contact` too? I don’t see anything left that calls it.

**Comment by jamiecobbett** [comment]
Yes, I'll do that now.

**Comment by jamiecobbett** [comment]
Rebased.

**Comment by fatbusinessman** [comment]
> Rebased.

Hurrah! `red++`

**Pull request merged**
