### PR TITLE
Index contacts in site search

### PR DESCRIPTION
**Pull request by jamiecobbett**
This means that:
* GOV.UK site search returns these pages, meaning users can find them without
  using an external search engine
* we can archive/redirect this page which works around the problem: https://www.gov.uk/contact-hmrc
* in principle, we can use a Finder to replace the public index/filter page

We should make sure all existing contacts are indexed when this is deployed. This should be trivial in the Rails console:
```ruby
Contacts.all.each do |contact|
  ::Contacts.rummager_client.add(contact.to_indexed_json)
end
```

### CODE REVIEW

**Comment by jamiecobbett** [comment]
I'm in the process of testing this in development.

**Comment by jamiecobbett** [comment]
Bump. @rboulton would you mind giving this a once-over? 

This is currently blocking moving the filter page to a finder.

**Comment by rboulton** [comment]
Looks good: merging.

**Comment by jamiecobbett** [comment]
:grinning:

**Pull request merged**
