### PR TITLE
Update deployment config

### PR DESCRIPTION
**Pull request by davidbasalla**
For https://trello.com/c/YbcsenXK/473-contacts-admin-dependency-maintenance-3

Changing to modern deployment approach, goes together with https://github.com/alphagov/govuk-puppet/pull/4845

### CODE REVIEW

**Comment by sihugh** [comment]
👍  merge when ready

**Comment by sihugh** [comment]
Hold for a minute, given that we're deleting `redis.yml` in https://github.gds/gds/alphagov-deployment/pull/1229, shouldn't we be applying the [env vars set in Puppet](https://github.com/alphagov/govuk-puppet/blob/9e6193ec3c7667521c077b8114b20ee770202ffe/hieradata/common.yaml#L250L251) to our current `redis.yml` rather than deleting it in this PR?

**Comment by davidbasalla** [comment]
Good catch @sihugh, thanks! Have updated to fix it, following what LocalLinksManager does

**Comment by sihugh** [comment]
:+1: merge when ready

**Pull request merged**
